### ISSUE TITLE
More Detail for implementation

### ISSUE THREAD

**Issue by wizare** [zhanghainan/STAR-BTM#1]
This is an interesting work that I would like to re-run on my dataset.  However， I don't know how to run your program and the format of the input dataset. What is even more confusing is that there is no `vocab` under `utils`, resulting in import error.
If possible, detailed implementation instructions would be appreciated.

**Comment by zhanghainan** [comment]
sorry, I forgot some files. Now I have upload these files in github. Thanks~

**Comment by wizare** [comment]
thanks for your reply! can you supply some toy data for input datasets?

**Comment by zhanghainan** [comment]
have upload~

**Comment by wizare** [comment]
Thank you for your enthusiastic answers！
