### ISSUE TITLE
The usage of the BTM

### ISSUE THREAD

**Issue by tonywenuon** [zhanghainan/STAR-BTM#2]
Really appreciate the implementation. I checked over the codes, but I did not find the usage of the BTM. I have two questions:

1.  Imagine that the BTM is generated from another repository, how to use it in the STAR-BTM model? 
2.  Could you please give a script example to show how to run the model?

Thanks very much!

**Comment by zhanghainan** [comment]
the train data has the topic tag in the front of the each sentence

**Comment by tonywenuon** [comment]
Got this. Thanks for your rapid reply! I'll try it.
